# Works: Ubuntu 18.04
network:
    ethernets:
        enp7s1:
            addresses:
            - 192.168.1.2/24
            gateway4: 192.168.1.1
            nameservers:
                addresses:
                - 8.8.8.8
                - 8.8.4.4
    version: 2